{{- if and .Values.externalSecrets.enabled .Values.rabbitmq.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
        erlang-cookie: "{{ `{{ .erlangCookie }}` }}"
  data:
  - secretKey: username
    remoteRef:
      key: rabbitmq/auth
      property: username
  - secretKey: password
    remoteRef:
      key: rabbitmq/auth
      property: password
  - secretKey: erlangCookie
    remoteRef:
      key: rabbitmq/auth
      property: erlang_cookie
{{- end }}
