{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
        database: "{{ `{{ .database }}` }}"
  data:
  - secretKey: username
    remoteRef:
      key: foodgram/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: foodgram/postgres
      property: password
  - secretKey: database
    remoteRef:
      key: foodgram/postgres
      property: database
{{- end }}
