{{- if and .Values.externalSecrets.enabled .Values.redis.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: redis/auth
      property: password
{{- end }}
