{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: django-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        secret-key: "{{ `{{ .secretKey }}` }}"
        debug: "{{ `{{ .debug }}` }}"
        allowed-hosts: "{{ `{{ .allowedHosts }}` }}"
  data:
  - secretKey: secretKey
    remoteRef:
      key: foodgram/django
      property: secret_key
  - secretKey: debug
    remoteRef:
      key: foodgram/django
      property: debug
  - secretKey: allowedHosts
    remoteRef:
      key: foodgram/django
      property: allowed_hosts
{{- end }}
