{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vault.server | quote }}
      path: {{ .Values.externalSecrets.vault.path | quote }}
      version: {{ .Values.externalSecrets.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.vault.auth.mountPath | quote }}
          role: {{ .Values.externalSecrets.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.vault.auth.serviceAccount | default "default" | quote }}
{{- end }}
