{
 "title": "NGINX Ingress",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Запросы в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total[5m])",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Активные соединения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_connections{state=\"active\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Память (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "RAM MB"
    }
   ]
  },
  {
   "title": "Сетевой трафик (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_write_bytes_total[5m]) / 1024",
     "legendFormat": "write KB/s"
    },
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_read_bytes_total[5m]) / 1024",
     "legendFormat": "read KB/s"
    }
   ]
  }
 ]
}