apiVersion: v2
name: foodgram
description: Foodgram application
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: backend
    version: "1.0.0"
    repository: "file://./charts/backend"
    condition: backend.enabled
  - name: frontend
    version: "1.0.0"
    repository: "file://./charts/frontend"
    condition: frontend.enabled
  - name: postgresql
    version: "1.0.0"
    repository: "file://./charts/postgresql"
    condition: postgresql.enabled
